export const getJournalEntries = {
  status_code: 200,
  status_code_class: "success",
  status_message: "OK",
  data: [
    {
      id: "jre_23131",
      journal_date: "2023-10-26",
      currency: "USD",
      currency_rate: 1.0,
      exchange_rate: 1.0,
      note: "Recording initial capital contribution",
      reference: "INIT-CAP-001",
      status: "approved",
      line_items: [
        {
          id: "jrei_111",
          account_id: "acc_001",
          account_name: "Cash",
          description: "Initial cash deposit",
          amount: 10000.0,
          tax_amount: 0.0,
          tax_rate: 0.0,
          tax_type: null,
          type: "debit",
        },
        {
          id: "jrei_112",
          account_id: "acc_002",
          account_name: "Owner's Equity",
          description: "Initial capital",
          amount: 10000.0,
          tax_amount: 0.0,
          tax_rate: 0.0,
          tax_type: null,
          type: "credit",
        },
      ],
      total_amount: 10000.0,
      balance: 0.0,
      custom_fields: [],
      row_version: "2023-10-26T10:00:00Z",
      updated_by: "user_abc",
      created_by: "user_abc",
      updated_at: "2023-10-26T10:00:00Z",
      created_at: "2023-10-26T10:00:00Z",
    },
    {
      id: "jre_23132",
      journal_date: "2023-10-27",
      currency: "USD",
      currency_rate: 1.0,
      exchange_rate: 1.0,
      note: "Recording office supply purchase",
      reference: "OFF-SUP-005",
      status: "approved",
      line_items: [
        {
          id: "jrei_221",
          account_id: "acc_003",
          account_name: "Office Supplies",
          description: "Purchase of pens and paper",
          amount: 150.5,
          tax_amount: 10.0,
          tax_rate: 0.07,
          tax_type: "GST",
          type: "debit",
        },
        {
          id: "jrei_222",
          account_id: "acc_004",
          account_name: "Accounts Payable",
          description: "Due to supplier XYZ",
          amount: 160.5,
          tax_amount: 0.0,
          tax_rate: 0.0,
          tax_type: null,
          type: "credit",
        },
      ],
      total_amount: 160.5,
      balance: 0.0,
      custom_fields: [
        {
          id: "cf_001",
          name: "Project Code",
          value: "PRJ-ALPHA",
        },
      ],
      row_version: "2023-10-27T14:30:00Z",
      updated_by: "user_xyz",
      created_by: "user_xyz",
      updated_at: "2023-10-27T14:30:00Z",
      created_at: "2023-10-27T14:30:00Z",
    },
    {
      id: "jre_23133",
      journal_date: "2023-10-28",
      currency: "EUR",
      currency_rate: 0.95,
      exchange_rate: 1.05,
      note: "Monthly rent payment",
      reference: "RENT-OCT-23",
      status: "approved",
      line_items: [
        {
          id: "jrei_331",
          account_id: "acc_005",
          account_name: "Rent Expense",
          description: "October office rent",
          amount: 2500.0,
          tax_amount: 0.0,
          tax_rate: 0.0,
          tax_type: null,
          type: "debit",
        },
        {
          id: "jrei_332",
          account_id: "acc_001",
          account_name: "Cash",
          description: "Paid to landlord",
          amount: 2500.0,
          tax_amount: 0.0,
          tax_rate: 0.0,
          tax_type: null,
          type: "credit",
        },
      ],
      total_amount: 2500.0,
      balance: 0.0,
      custom_fields: [],
      row_version: "2023-10-28T09:00:00Z",
      updated_by: "user_abc",
      created_by: "user_abc",
      updated_at: "2023-10-28T09:00:00Z",
      created_at: "2023-10-28T09:00:00Z",
    },
    {
      id: "jre_23134",
      journal_date: "2023-10-29",
      currency: "USD",
      currency_rate: 1.0,
      exchange_rate: 1.0,
      note: "Sale of services to client A",
      reference: "INV-0010",
      status: "approved",
      line_items: [
        {
          id: "jrei_441",
          account_id: "acc_006",
          account_name: "Accounts Receivable",
          description: "Invoice #0010 for services",
          amount: 1200.0,
          tax_amount: 0.0,
          tax_rate: 0.0,
          tax_type: null,
          type: "debit",
        },
        {
          id: "jrei_442",
          account_id: "acc_007",
          account_name: "Service Revenue",
          description: "Revenue from client A",
          amount: 1200.0,
          tax_amount: 0.0,
          tax_rate: 0.0,
          tax_type: null,
          type: "credit",
        },
      ],
      total_amount: 1200.0,
      balance: 0.0,
      custom_fields: [],
      row_version: "2023-10-29T11:20:00Z",
      updated_by: "user_xyz",
      created_by: "user_xyz",
      updated_at: "2023-10-29T11:20:00Z",
      created_at: "2023-10-29T11:20:00Z",
    },
    {
      id: "jre_23135",
      journal_date: "2023-10-30",
      currency: "GBP",
      currency_rate: 0.82,
      exchange_rate: 1.22,
      note: "Payment for software subscription",
      reference: "SUB-SFWR-001",
      status: "approved",
      line_items: [
        {
          id: "jrei_551",
          account_id: "acc_008",
          account_name: "Software Expense",
          description: "Annual software license",
          amount: 300.0,
          tax_amount: 0.0,
          tax_rate: 0.0,
          tax_type: null,
          type: "debit",
        },
        {
          id: "jrei_552",
          account_id: "acc_001",
          account_name: "Cash",
          description: "Paid to vendor",
          amount: 300.0,
          tax_amount: 0.0,
          tax_rate: 0.0,
          tax_type: null,
          type: "credit",
        },
      ],
      total_amount: 300.0,
      balance: 0.0,
      custom_fields: [],
      row_version: "2023-10-30T16:00:00Z",
      updated_by: "user_abc",
      created_by: "user_abc",
      updated_at: "2023-10-30T16:00:00Z",
      created_at: "2023-10-30T16:00:00Z",
    },
    {
      id: "jre_23136",
      journal_date: "2023-10-31",
      currency: "USD",
      currency_rate: 1.0,
      exchange_rate: 1.0,
      note: "Employee payroll expenses",
      reference: "PAYROLL-OCT-23",
      status: "approved",
      line_items: [
        {
          id: "jrei_661",
          account_id: "acc_009",
          account_name: "Salary Expense",
          description: "October salaries",
          amount: 5000.0,
          tax_amount: 0.0,
          tax_rate: 0.0,
          tax_type: null,
          type: "debit",
        },
        {
          id: "jrei_662",
          account_id: "acc_010",
          account_name: "Payroll Payable",
          description: "Net pay due",
          amount: 4000.0,
          tax_amount: 0.0,
          tax_rate: 0.0,
          tax_type: null,
          type: "credit",
        },
        {
          id: "jrei_663",
          account_id: "acc_011",
          account_name: "Withholding Taxes Payable",
          description: "Taxes withheld",
          amount: 1000.0,
          tax_amount: 0.0,
          tax_rate: 0.0,
          tax_type: null,
          type: "credit",
        },
      ],
      total_amount: 5000.0,
      balance: 0.0,
      custom_fields: [],
      row_version: "2023-10-31T08:30:00Z",
      updated_by: "user_hr",
      created_by: "user_hr",
      updated_at: "2023-10-31T08:30:00Z",
      created_at: "2023-10-31T08:30:00Z",
    },
    {
      id: "jre_23137",
      journal_date: "2023-11-01",
      currency: "USD",
      currency_rate: 1.0,
      exchange_rate: 1.0,
      note: "Bank loan principal payment",
      reference: "LOAN-PMT-01",
      status: "approved",
      line_items: [
        {
          id: "jrei_771",
          account_id: "acc_012",
          account_name: "Loans Payable",
          description: "Principal payment on bank loan",
          amount: 1000.0,
          tax_amount: 0.0,
          tax_rate: 0.0,
          tax_type: null,
          type: "debit",
        },
        {
          id: "jrei_772",
          account_id: "acc_001",
          account_name: "Cash",
          description: "Cash outflow for loan",
          amount: 1000.0,
          tax_amount: 0.0,
          tax_rate: 0.0,
          tax_type: null,
          type: "credit",
        },
      ],
      total_amount: 1000.0,
      balance: 0.0,
      custom_fields: [],
      row_version: "2023-11-01T10:00:00Z",
      updated_by: "user_finance",
      created_by: "user_finance",
      updated_at: "2023-11-01T10:00:00Z",
      created_at: "2023-11-01T10:00:00Z",
    },
    {
      id: "jre_23138",
      journal_date: "2023-11-02",
      currency: "USD",
      currency_rate: 1.0,
      exchange_rate: 1.0,
      note: "Interest expense on loan",
      reference: "INT-EXP-01",
      status: "approved",
      line_items: [
        {
          id: "jrei_881",
          account_id: "acc_013",
          account_name: "Interest Expense",
          description: "Monthly interest on bank loan",
          amount: 50.0,
          tax_amount: 0.0,
          tax_rate: 0.0,
          tax_type: null,
          type: "debit",
        },
        {
          id: "jrei_882",
          account_id: "acc_001",
          account_name: "Cash",
          description: "Cash outflow for interest",
          amount: 50.0,
          tax_amount: 0.0,
          tax_rate: 0.0,
          tax_type: null,
          type: "credit",
        },
      ],
      total_amount: 50.0,
      balance: 0.0,
      custom_fields: [],
      row_version: "2023-11-02T11:00:00Z",
      updated_by: "user_finance",
      created_by: "user_finance",
      updated_at: "2023-11-02T11:00:00Z",
      created_at: "2023-11-02T11:00:00Z",
    },
    {
      id: "jre_23139",
      journal_date: "2023-11-03",
      currency: "USD",
      currency_rate: 1.0,
      exchange_rate: 1.0,
      note: "Purchase of new computer equipment",
      reference: "EQUIP-001",
      status: "approved",
      line_items: [
        {
          id: "jrei_991",
          account_id: "acc_014",
          account_name: "Computer Equipment",
          description: "New laptop for design team",
          amount: 1500.0,
          tax_amount: 105.0,
          tax_rate: 0.07,
          tax_type: "GST",
          type: "debit",
        },
        {
          id: "jrei_992",
          account_id: "acc_004",
          account_name: "Accounts Payable",
          description: "Due to electronics supplier",
          amount: 1605.0,
          tax_amount: 0.0,
          tax_rate: 0.0,
          tax_type: null,
          type: "credit",
        },
      ],
      total_amount: 1605.0,
      balance: 0.0,
      custom_fields: [],
      row_version: "2023-11-03T14:00:00Z",
      updated_by: "user_it",
      created_by: "user_it",
      updated_at: "2023-11-03T14:00:00Z",
      created_at: "2023-11-03T14:00:00Z",
    },
    {
      id: "jre_23140",
      journal_date: "2023-11-04",
      currency: "USD",
      currency_rate: 1.0,
      exchange_rate: 1.0,
      note: "Receipt of cash from client B",
      reference: "REC-CLI-B",
      status: "approved",
      line_items: [
        {
          id: "jrei_1001",
          account_id: "acc_001",
          account_name: "Cash",
          description: "Payment from client B for services",
          amount: 800.0,
          tax_amount: 0.0,
          tax_rate: 0.0,
          tax_type: null,
          type: "debit",
        },
        {
          id: "jrei_1002",
          account_id: "acc_006",
          account_name: "Accounts Receivable",
          description: "Clearing client B's receivable",
          amount: 800.0,
          tax_amount: 0.0,
          tax_rate: 0.0,
          tax_type: null,
          type: "credit",
        },
      ],
      total_amount: 800.0,
      balance: 0.0,
      custom_fields: [],
      row_version: "2023-11-04T10:30:00Z",
      updated_by: "user_finance",
      created_by: "user_finance",
      updated_at: "2023-11-04T10:30:00Z",
      created_at: "2023-11-04T10:30:00Z",
    },
    {
      id: "jre_23141",
      journal_date: "2023-11-05",
      currency: "USD",
      currency_rate: 1.0,
      exchange_rate: 1.0,
      note: "Office renovation expense",
      reference: "REN-001",
      status: "approved",
      line_items: [
        {
          id: "jrei_1101",
          account_id: "acc_015",
          account_name: "Repairs and Maintenance",
          description: "Minor office improvements",
          amount: 750.0,
          tax_amount: 52.5,
          tax_rate: 0.07,
          tax_type: "GST",
          type: "debit",
        },
        {
          id: "jrei_1102",
          account_id: "acc_001",
          account_name: "Cash",
          description: "Paid to contractor",
          amount: 802.5,
          tax_amount: 0.0,
          tax_rate: 0.0,
          tax_type: null,
          type: "credit",
        },
      ],
      total_amount: 802.5,
      balance: 0.0,
      custom_fields: [],
      row_version: "2023-11-05T09:45:00Z",
      updated_by: "user_admin",
      created_by: "user_admin",
      updated_at: "2023-11-05T09:45:00Z",
      created_at: "2023-11-05T09:45:00Z",
    },
    {
      id: "jre_23142",
      journal_date: "2023-11-06",
      currency: "USD",
      currency_rate: 1.0,
      exchange_rate: 1.0,
      note: "Advertising campaign payment",
      reference: "AD-CAMP-003",
      status: "approved",
      line_items: [
        {
          id: "jrei_1201",
          account_id: "acc_016",
          account_name: "Advertising Expense",
          description: "Online ad spend for November",
          amount: 400.0,
          tax_amount: 0.0,
          tax_rate: 0.0,
          tax_type: null,
          type: "debit",
        },
        {
          id: "jrei_1202",
          account_id: "acc_001",
          account_name: "Cash",
          description: "Payment to ad platform",
          amount: 400.0,
          tax_amount: 0.0,
          tax_rate: 0.0,
          tax_type: null,
          type: "credit",
        },
      ],
      total_amount: 400.0,
      balance: 0.0,
      custom_fields: [],
      row_version: "2023-11-06T15:00:00Z",
      updated_by: "user_marketing",
      created_by: "user_marketing",
      updated_at: "2023-11-06T15:00:00Z",
      created_at: "2023-11-06T15:00:00Z",
    },
    {
      id: "jre_23143",
      journal_date: "2023-11-07",
      currency: "USD",
      currency_rate: 1.0,
      exchange_rate: 1.0,
      note: "Utilities payment (electricity)",
      reference: "UTIL-NOV-ELEC",
      status: "approved",
      line_items: [
        {
          id: "jrei_1301",
          account_id: "acc_017",
          account_name: "Utilities Expense",
          description: "November electricity bill",
          amount: 120.0,
          tax_amount: 0.0,
          tax_rate: 0.0,
          tax_type: null,
          type: "debit",
        },
        {
          id: "jrei_1302",
          account_id: "acc_001",
          account_name: "Cash",
          description: "Paid to utility company",
          amount: 120.0,
          tax_amount: 0.0,
          tax_rate: 0.0,
          tax_type: null,
          type: "credit",
        },
      ],
      total_amount: 120.0,
      balance: 0.0,
      custom_fields: [],
      row_version: "2023-11-07T10:15:00Z",
      updated_by: "user_admin",
      created_by: "user_admin",
      updated_at: "2023-11-07T10:15:00Z",
      created_at: "2023-11-07T10:15:00Z",
    },
    {
      id: "jre_23144",
      journal_date: "2023-11-08",
      currency: "USD",
      currency_rate: 1.0,
      exchange_rate: 1.0,
      note: "Consulting fees received",
      reference: "CONSULT-INV-005",
      status: "approved",
      line_items: [
        {
          id: "jrei_1401",
          account_id: "acc_001",
          account_name: "Cash",
          description: "Received for consulting services",
          amount: 2000.0,
          tax_amount: 0.0,
          tax_rate: 0.0,
          tax_type: null,
          type: "debit",
        },
        {
          id: "jrei_1402",
          account_id: "acc_007",
          account_name: "Service Revenue",
          description: "Revenue from consulting",
          amount: 2000.0,
          tax_amount: 0.0,
          tax_rate: 0.0,
          tax_type: null,
          type: "credit",
        },
      ],
      total_amount: 2000.0,
      balance: 0.0,
      custom_fields: [],
      row_version: "2023-11-08T13:00:00Z",
      updated_by: "user_finance",
      created_by: "user_finance",
      updated_at: "2023-11-08T13:00:00Z",
      created_at: "2023-11-08T13:00:00Z",
    },
    {
      id: "jre_23145",
      journal_date: "2023-11-09",
      currency: "USD",
      currency_rate: 1.0,
      exchange_rate: 1.0,
      note: "Purchase of raw materials",
      reference: "RM-PUR-020",
      status: "approved",
      line_items: [
        {
          id: "jrei_1501",
          account_id: "acc_018",
          account_name: "Raw Materials Inventory",
          description: "Purchase from supplier M",
          amount: 3500.0,
          tax_amount: 245.0,
          tax_rate: 0.07,
          tax_type: "GST",
          type: "debit",
        },
        {
          id: "jrei_1502",
          account_id: "acc_004",
          account_name: "Accounts Payable",
          description: "Due to supplier M",
          amount: 3745.0,
          tax_amount: 0.0,
          tax_rate: 0.0,
          tax_type: null,
          type: "credit",
        },
      ],
      total_amount: 3745.0,
      balance: 0.0,
      custom_fields: [],
      row_version: "2023-11-09T09:00:00Z",
      updated_by: "user_ops",
      created_by: "user_ops",
      updated_at: "2023-11-09T09:00:00Z",
      created_at: "2023-11-09T09:00:00Z",
    },
    {
      id: "jre_23146",
      journal_date: "2023-11-10",
      currency: "USD",
      currency_rate: 1.0,
      exchange_rate: 1.0,
      note: "Bank service charges",
      reference: "BANK-CHG-NOV",
      status: "approved",
      line_items: [
        {
          id: "jrei_1601",
          account_id: "acc_019",
          account_name: "Bank Service Charges",
          description: "Monthly bank fees",
          amount: 25.0,
          tax_amount: 0.0,
          tax_rate: 0.0,
          tax_type: null,
          type: "debit",
        },
        {
          id: "jrei_1602",
          account_id: "acc_001",
          account_name: "Cash",
          description: "Deducted from bank account",
          amount: 25.0,
          tax_amount: 0.0,
          tax_rate: 0.0,
          tax_type: null,
          type: "credit",
        },
      ],
      total_amount: 25.0,
      balance: 0.0,
      custom_fields: [],
      row_version: "2023-11-10T11:00:00Z",
      updated_by: "user_finance",
      created_by: "user_finance",
      updated_at: "2023-11-10T11:00:00Z",
      created_at: "2023-11-10T11:00:00Z",
    },
    {
      id: "jre_23147",
      journal_date: "2023-11-11",
      currency: "USD",
      currency_rate: 1.0,
      exchange_rate: 1.0,
      note: "Sales revenue with sales tax",
      reference: "INV-0011",
      status: "approved",
      line_items: [
        {
          id: "jrei_1701",
          account_id: "acc_006",
          account_name: "Accounts Receivable",
          description: "Invoice #0011 for goods sold",
          amount: 500,
          tax_amount: 35.0,
          tax_rate: 0.07,
          tax_type: "Sales Tax",
          type: "debit",
        },
        {
          id: "jrei_1702",
          account_id: "acc_007",
          account_name: "Sales Revenue",
          description: "Revenue from goods sold",
          amount: 500.0,
          tax_amount: 0.0,
          tax_rate: 0.0,
          tax_type: null,
          type: "credit",
        },
        {
          id: "jrei_1703",
          account_id: "acc_020",
          account_name: "Sales Tax Payable",
          description: "Sales tax collected",
          amount: 35.0,
          tax_amount: 0.0,
          tax_rate: 0.0,
          tax_type: null,
          type: "credit",
        },
      ],
      total_amount: 535.0,
      balance: 0.0,
      custom_fields: [],
      row_version: "2023-11-11T14:30:00Z",
      updated_by: "user_sales",
      created_by: "user_sales",
      updated_at: "2023-11-11T14:30:00Z",
      created_at: "2023-11-11T14:30:00Z",
    },
    {
      id: "jre_23148",
      journal_date: "2023-11-12",
      currency: "USD",
      currency_rate: 1.0,
      exchange_rate: 1.0,
      note: "Payment of accounts payable (supplier XYZ)",
      reference: "PAY-SUP-XYZ",
      status: "approved",
      line_items: [
        {
          id: "jrei_1801",
          account_id: "acc_004",
          account_name: "Accounts Payable",
          description: "Payment to supplier XYZ",
          amount: 160.5,
          tax_amount: 0.0,
          tax_rate: 0.0,
          tax_type: null,
          type: "debit",
        },
        {
          id: "jrei_1802",
          account_id: "acc_001",
          account_name: "Cash",
          description: "Cash outflow for payment",
          amount: 160.5,
          tax_amount: 0.0,
          tax_rate: 0.0,
          tax_type: null,
          type: "credit",
        },
      ],
      total_amount: 160.5,
      balance: 0.0,
      custom_fields: [],
      row_version: "2023-11-12T10:00:00Z",
      updated_by: "user_finance",
      created_by: "user_finance",
      updated_at: "2023-11-12T10:00:00Z",
      created_at: "2023-11-12T10:00:00Z",
    },
    {
      id: "jre_23149",
      journal_date: "2023-11-13",
      currency: "USD",
      currency_rate: 1.0,
      exchange_rate: 1.0,
      note: "Depreciation expense for the month",
      reference: "DEPR-NOV-23",
      status: "approved",
      line_items: [
        {
          id: "jrei_1901",
          account_id: "acc_021",
          account_name: "Depreciation Expense",
          description: "November depreciation on fixed assets",
          amount: 500.0,
          tax_amount: 0.0,
          tax_rate: 0.0,
          tax_type: null,
          type: "debit",
        },
        {
          id: "jrei_1902",
          account_id: "acc_022",
          account_name: "Accumulated Depreciation",
          description: "Accumulated depreciation for November",
          amount: 500.0,
          tax_amount: 0.0,
          tax_rate: 0.0,
          tax_type: null,
          type: "credit",
        },
      ],
      total_amount: 500.0,
      balance: 0.0,
      custom_fields: [],
      row_version: "2023-11-13T16:00:00Z",
      updated_by: "user_accountant",
      created_by: "user_accountant",
      updated_at: "2023-11-13T16:00:00Z",
      created_at: "2023-11-13T16:00:00Z",
    },
    {
      id: "jre_23150",
      journal_date: "2023-11-14",
      currency: "USD",
      currency_rate: 1.0,
      exchange_rate: 1.0,
      note: "Prepaid insurance adjustment",
      reference: "PREPAID-INS-ADJ",
      status: "approved",
      line_items: [
        {
          id: "jrei_2001",
          account_id: "acc_023",
          account_name: "Insurance Expense",
          description: "Recognition of insurance expense",
          amount: 100.0,
          tax_amount: 0.0,
          tax_rate: 0.0,
          tax_type: null,
          type: "debit",
        },
        {
          id: "jrei_2002",
          account_id: "acc_024",
          account_name: "Prepaid Insurance",
          description: "Reduction in prepaid insurance",
          amount: 100.0,
          tax_amount: 0.0,
          tax_rate: 0.0,
          tax_type: null,
          type: "credit",
        },
      ],
      total_amount: 100.0,
      balance: 0.0,
      custom_fields: [],
      row_version: "2023-11-14T11:00:00Z",
      updated_by: "user_accountant",
      created_by: "user_accountant",
      updated_at: "2023-11-14T11:00:00Z",
      created_at: "2023-11-14T11:00:00Z",
    },
    {
      id: "jre_23151",
      journal_date: "2023-11-15",
      currency: "USD",
      currency_rate: 1.0,
      exchange_rate: 1.0,
      note: "Accrued salaries for mid-month",
      reference: "ACCRUED-SAL-MID",
      status: "approved",
      line_items: [
        {
          id: "jrei_2101",
          account_id: "acc_009",
          account_name: "Salary Expense",
          description: "Accrued salaries for first half of November",
          amount: 2500.0,
          tax_amount: 0.0,
          tax_rate: 0.0,
          tax_type: null,
          type: "debit",
        },
        {
          id: "jrei_2102",
          account_id: "acc_010",
          account_name: "Payroll Payable",
          description: "Salaries owed to employees",
          amount: 2500.0,
          tax_amount: 0.0,
          tax_rate: 0.0,
          tax_type: null,
          type: "credit",
        },
      ],
      total_amount: 2500.0,
      balance: 0.0,
      custom_fields: [],
      row_version: "2023-11-15T17:00:00Z",
      updated_by: "user_hr",
      created_by: "user_hr",
      updated_at: "2023-11-15T17:00:00Z",
      created_at: "2023-11-15T17:00:00Z",
    },
    {
      id: "jre_23152",
      journal_date: "2023-11-16",
      currency: "USD",
      currency_rate: 1.0,
      exchange_rate: 1.0,
      note: "Receipt for a small refund",
      reference: "REFUND-001",
      status: "approved",
      line_items: [
        {
          id: "jrei_2201",
          account_id: "acc_001",
          account_name: "Cash",
          description: "Refund from a supplier",
          amount: 75.0,
          tax_amount: 0.0,
          tax_rate: 0.0,
          tax_type: null,
          type: "debit",
        },
        {
          id: "jrei_2202",
          account_id: "acc_003",
          account_name: "Office Supplies",
          description: "Credit for returned supplies",
          amount: 75.0,
          tax_amount: 0.0,
          tax_rate: 0.0,
          tax_type: null,
          type: "credit",
        },
      ],
      total_amount: 75.0,
      balance: 0.0,
      custom_fields: [],
      row_version: "2023-11-16T09:00:00Z",
      updated_by: "user_admin",
      created_by: "user_admin",
      updated_at: "2023-11-16T09:00:00Z",
      created_at: "2023-11-16T09:00:00Z",
    },
    {
      id: "jre_23153",
      journal_date: "2023-11-17",
      currency: "USD",
      currency_rate: 1.0,
      exchange_rate: 1.0,
      note: "Investment in short-term securities",
      reference: "INVEST-SHRT-001",
      status: "approved",
      line_items: [
        {
          id: "jrei_2301",
          account_id: "acc_025",
          account_name: "Short-term Investments",
          description: "Purchase of marketable securities",
          amount: 5000.0,
          tax_amount: 0.0,
          tax_rate: 0.0,
          tax_type: null,
          type: "debit",
        },
        {
          id: "jrei_2302",
          account_id: "acc_001",
          account_name: "Cash",
          description: "Cash used for investment",
          amount: 5000.0,
          tax_amount: 0.0,
          tax_rate: 0.0,
          tax_type: null,
          type: "credit",
        },
      ],
      total_amount: 5000.0,
      balance: 0.0,
      custom_fields: [],
      row_version: "2023-11-17T13:00:00Z",
      updated_by: "user_finance",
      created_by: "user_finance",
      updated_at: "2023-11-17T13:00:00Z",
      created_at: "2023-11-17T13:00:00Z",
    },
    {
      id: "jre_23154",
      journal_date: "2023-11-18",
      currency: "USD",
      currency_rate: 1.0,
      exchange_rate: 1.0,
      note: "Dividend income received",
      reference: "DIV-INC-001",
      status: "approved",
      line_items: [
        {
          id: "jrei_2401",
          account_id: "acc_001",
          account_name: "Cash",
          description: "Dividend from investments",
          amount: 150.0,
          tax_amount: 0.0,
          tax_rate: 0.0,
          tax_type: null,
          type: "debit",
        },
        {
          id: "jrei_2402",
          account_id: "acc_026",
          account_name: "Dividend Income",
          description: "Income from securities",
          amount: 150.0,
          tax_amount: 0.0,
          tax_rate: 0.0,
          tax_type: null,
          type: "credit",
        },
      ],
      total_amount: 150.0,
      balance: 0.0,
      custom_fields: [],
      row_version: "2023-11-18T10:00:00Z",
      updated_by: "user_finance",
      created_by: "user_finance",
      updated_at: "2023-11-18T10:00:00Z",
      created_at: "2023-11-18T10:00:00Z",
    },
    {
      id: "jre_23155",
      journal_date: "2023-11-19",
      currency: "USD",
      currency_rate: 1.0,
      exchange_rate: 1.0,
      note: "Refund to customer for returned goods",
      reference: "CUST-REFUND-002",
      status: "approved",
      line_items: [
        {
          id: "jrei_2501",
          account_id: "acc_007",
          account_name: "Sales Returns and Allowances",
          description: "Refund for product return",
          amount: 90.0,
          tax_amount: 0.0,
          tax_rate: 0.0,
          tax_type: null,
          type: "debit",
        },
        {
          id: "jrei_2502",
          account_id: "acc_001",
          account_name: "Cash",
          description: "Cash outflow for customer refund",
          amount: 90.0,
          tax_amount: 0.0,
          tax_rate: 0.0,
          tax_type: null,
          type: "credit",
        },
      ],
      total_amount: 90.0,
      balance: 0.0,
      custom_fields: [],
      row_version: "2023-11-19T11:45:00Z",
      updated_by: "user_sales",
      created_by: "user_sales",
      updated_at: "2023-11-19T11:45:00Z",
      created_at: "2023-11-19T11:45:00Z",
    },
  ],
  links: {
    current:
      "https://api.apideck.com/accounting/v2/consumers/consumerId/connections/connectionId/journal-entries",
    next: "https://api.apideck.com/accounting/v2/consumers/consumerId/connections/connectionId/journal-entries?cursor=jre_23155",
    previous: null,
  },
  meta: {
    total_count: 20,
    cursor: "jre_23155",
  },
};

// ############################################################################################################


export const getLedgerAccounts = [
  {
    "id": "acc_001",
    "name": "Cash on Hand",
    "description": "Physical cash held by the business.",
    "code": "1000",
    "type": "asset",
    "status": "active",
    "currency": "USD",
    "balance": 1500.00,
    "current_balance": 1450.75,
    "sub_accounts": [],
    "last_modified_at": "2023-10-27T10:00:00Z",
    "created_at": "2023-01-01T09:00:00Z"
  },
  {
    "id": "acc_002",
    "name": "Bank Account (Checking)",
    "description": "Main operational checking account.",
    "code": "1010",
    "type": "asset",
    "status": "active",
    "currency": "USD",
    "balance": 25000.50,
    "current_balance": 24890.20,
    "sub_accounts": [],
    "last_modified_at": "2023-10-27T10:30:00Z",
    "created_at": "2023-01-01T09:05:00Z"
  },
  {
    "id": "acc_003",
    "name": "Accounts Receivable",
    "description": "Money owed to the business by customers.",
    "code": "1200",
    "type": "asset",
    "status": "active",
    "currency": "USD",
    "balance": 10500.00,
    "current_balance": 9875.50,
    "sub_accounts": [],
    "last_modified_at": "2023-10-27T11:00:00Z",
    "created_at": "2023-01-01T09:10:00Z"
  },
  {
    "id": "acc_004",
    "name": "Office Equipment",
    "description": "Fixed assets like computers, printers, etc.",
    "code": "1500",
    "type": "asset",
    "status": "active",
    "currency": "USD",
    "balance": 7500.00,
    "current_balance": 6800.00, // Accumulated depreciation might reduce current balance visually
    "sub_accounts": [],
    "last_modified_at": "2023-10-26T14:00:00Z",
    "created_at": "2023-02-15T10:00:00Z"
  },
  {
    "id": "acc_005",
    "name": "Accounts Payable",
    "description": "Money the business owes to suppliers.",
    "code": "2000",
    "type": "liability",
    "status": "active",
    "currency": "USD",
    "balance": -4000.00, // Liabilities often shown as negative balance in some systems
    "current_balance": -3800.00,
    "sub_accounts": [],
    "last_modified_at": "2023-10-27T11:30:00Z",
    "created_at": "2023-01-01T09:15:00Z"
  },
  {
    "id": "acc_006",
    "name": "Salaries Payable",
    "description": "Salaries owed to employees.",
    "code": "2100",
    "type": "liability",
    "status": "active",
    "currency": "USD",
    "balance": -3000.00,
    "current_balance": -3000.00,
    "sub_accounts": [],
    "last_modified_at": "2023-10-27T09:00:00Z",
    "created_at": "2023-03-01T12:00:00Z"
  },
  {
    "id": "acc_007",
    "name": "Sales Revenue",
    "description": "Income from product/service sales.",
    "code": "4000",
    "type": "revenue",
    "status": "active",
    "currency": "USD",
    "balance": 0.00, // Revenue accounts usually reset at year-end, current balance reflects period's total
    "current_balance": 50000.00,
    "sub_accounts": [],
    "last_modified_at": "2023-10-27T12:00:00Z",
    "created_at": "2023-01-01T09:20:00Z"
  },
  {
    "id": "acc_008",
    "name": "Rent Expense",
    "description": "Cost of office rent.",
    "code": "6000",
    "type": "expense",
    "status": "active",
    "currency": "USD",
    "balance": 0.00, // Expense accounts usually reset at year-end, current balance reflects period's total
    "current_balance": -1200.00,
    "sub_accounts": [],
    "last_modified_at": "2023-10-27T08:00:00Z",
    "created_at": "2023-01-01T09:25:00Z"
  },
  {
    "id": "acc_009",
    "name": "Utilities Expense",
    "description": "Cost of electricity, water, internet.",
    "code": "6100",
    "type": "expense",
    "status": "active",
    "currency": "USD",
    "balance": 0.00,
    "current_balance": -350.00,
    "sub_accounts": [],
    "last_modified_at": "2023-10-27T08:15:00Z",
    "created_at": "2023-01-01T09:30:00Z"
  },
  {
    "id": "acc_010",
    "name": "Owner's Equity",
    "description": "Owner's investment in the business.",
    "code": "3000",
    "type": "equity",
    "status": "active",
    "currency": "USD",
    "balance": 20000.00,
    "current_balance": 22000.00,
    "sub_accounts": [],
    "last_modified_at": "2023-10-25T16:00:00Z",
    "created_at": "2023-01-01T09:35:00Z"
  },
  {
    "id": "acc_011",
    "name": "Suspense Account",
    "description": "Temporary holding account for transactions that can't be immediately categorized.",
    "code": "9999",
    "type": "other",
    "status": "active",
    "currency": "USD",
    "balance": 0.00,
    "current_balance": 0.00,
    "sub_accounts": [],
    "last_modified_at": "2023-10-20T10:00:00Z",
    "created_at": "2023-05-01T10:00:00Z"
  }
];



// ###################################################################################################


export const getProfitAndLoss = {
  "getProfitAndLossResponse": {
    "data": {
      "id": "pfl_12345",
      "report_name": "Profit and Loss Statement",
      "currency": "USD",
      "start_date": "2023-01-01",
      "end_date": "2023-12-31",
      "sections": [
        {
          "id": "income_section",
          "name": "Income",
          "type": "income",
          "items": [
            {
              "id": "sales_revenue",
              "name": "Sales Revenue",
              "value": 150000.00,
              "currency": "USD",
              "type": "account_balance"
            },
            {
              "id": "other_income",
              "name": "Other Income",
              "value": 5000.00,
              "currency": "USD",
              "type": "account_balance"
            }
          ],
          "total": {
            "value": 155000.00,
            "currency": "USD"
          }
        },
        {
          "id": "cost_of_goods_sold_section",
          "name": "Cost of Goods Sold",
          "type": "cogs",
          "items": [
            {
              "id": "cost_of_sales",
              "name": "Cost of Sales",
              "value": 60000.00,
              "currency": "USD",
              "type": "account_balance"
            }
          ],
          "total": {
            "value": 60000.00,
            "currency": "USD"
          }
        },
        {
          "id": "gross_profit_section",
          "name": "Gross Profit",
          "type": "gross_profit",
          "items": [],
          "total": {
            "value": 95000.00,
            "currency": "USD"
          }
        },
        {
          "id": "operating_expenses_section",
          "name": "Operating Expenses",
          "type": "expense",
          "items": [
            {
              "id": "salaries",
              "name": "Salaries & Wages",
              "value": 30000.00,
              "currency": "USD",
              "type": "account_balance"
            },
            {
              "id": "rent",
              "name": "Rent Expense",
              "value": 12000.00,
              "currency": "USD",
              "type": "account_balance"
            },
            {
              "id": "utilities",
              "name": "Utilities",
              "value": 3000.00,
              "currency": "USD",
              "type": "account_balance"
            },
            {
              "id": "marketing",
              "name": "Marketing & Advertising",
              "value": 5000.00,
              "currency": "USD",
              "type": "account_balance"
            },
            {
              "id": "other_operating_expenses",
              "name": "Other Operating Expenses",
              "value": 2000.00,
              "currency": "USD",
              "type": "account_balance"
            }
          ],
          "total": {
            "value": 52000.00,
            "currency": "USD"
          }
        },
        {
          "id": "net_operating_income_section",
          "name": "Net Operating Income",
          "type": "net_operating_income",
          "items": [],
          "total": {
            "value": 43000.00,
            "currency": "USD"
          }
        },
        {
          "id": "other_expenses_section",
          "name": "Other Expenses",
          "type": "other_expense",
          "items": [
            {
              "id": "interest_expense",
              "name": "Interest Expense",
              "value": 1000.00,
              "currency": "USD",
              "type": "account_balance"
            }
          ],
          "total": {
            "value": 1000.00,
            "currency": "USD"
          }
        },
        {
          "id": "net_profit_section",
          "name": "Net Profit",
          "type": "net_profit",
          "items": [],
          "total": {
            "value": 42000.00,
            "currency": "USD"
          }
        }
      ]
    }
  }
}



// ##########################################################################################################



export const getBalanceSheet = {
  "getBalanceSheetResponse": {
    "data": {
      "reportName": "Balance Sheet",
      "currency": "USD",
      "reportDate": "2023-10-26", // Current date
      "assets": {
        "currentAssets": {
          "total": 85000.00,
          "accounts": [
            {
              "id": "cash_bank",
              "name": "Cash and Bank",
              "value": 30000.00,
              "type": "asset"
            },
            {
              "id": "accounts_receivable",
              "name": "Accounts Receivable",
              "value": 45000.00,
              "type": "asset"
            },
            {
              "id": "inventory",
              "name": "Inventory",
              "value": 10000.00,
              "type": "asset"
            }
          ]
        },
        "nonCurrentAssets": {
          "total": 120000.00,
          "accounts": [
            {
              "id": "property_plant_equipment",
              "name": "Property, Plant & Equipment",
              "value": 150000.00,
              "type": "asset"
            },
            {
              "id": "accumulated_depreciation",
              "name": "Accumulated Depreciation",
              "value": -30000.00, // Negative value for contra-asset
              "type": "asset"
            }
          ]
        },
        "totalAssets": 205000.00 // Sum of currentAssets.total + nonCurrentAssets.total
      },
      "liabilities": {
        "currentLiabilities": {
          "total": 35000.00,
          "accounts": [
            {
              "id": "accounts_payable",
              "name": "Accounts Payable",
              "value": 20000.00,
              "type": "liability"
            },
            {
              "id": "short_term_loans",
              "name": "Short-term Loans",
              "value": 10000.00,
              "type": "liability"
            },
            {
              "id": "accrued_expenses",
              "name": "Accrued Expenses",
              "value": 5000.00,
              "type": "liability"
            }
          ]
        },
        "nonCurrentLiabilities": {
          "total": 40000.00,
          "accounts": [
            {
              "id": "long_term_debt",
              "name": "Long-term Debt",
              "value": 40000.00,
              "type": "liability"
            }
          ]
        },
        "totalLiabilities": 75000.00 // Sum of currentLiabilities.total + nonCurrentLiabilities.total
      },
      "equity": {
        "total": 130000.00, // totalAssets - totalLiabilities
        "accounts": [
          {
            "id": "owner_equity",
            "name": "Owner's Equity",
            "value": 100000.00,
            "type": "equity"
          },
          {
            "id": "retained_earnings",
            "name": "Retained Earnings",
            "value": 30000.00,
            "type": "equity"
          }
        ]
      },
      "totalLiabilitiesAndEquity": 205000.00 // totalLiabilities + equity.total, should equal totalAssets
    }
  }
};