export const NEW_CLASSIFICATION_OPTIONS = [
    "Assets > Non-current > Intangible assets > Intangible assets - Cost",
    "Assets > Non-current > Intangible assets > Intangible assets - Accumulated Amortisation",
    "Assets > Non-current > Property, plant and equipment > Property, plant and equipment - Cost",
    "Assets > Non-current > Property, plant and equipment > Property, plant and equipment - Accumulated Depreciation",
    "Assets > Non-current > Investment property > Investment property - Cost",
    "Assets > Non-current > Investment property > Investment property - Accumulated Depreciation",
    "Assets > Non-current > Investment in subsidiary > Carrying amount",
    "Assets > Non-current > Investment in subsidiary > Share of profit for the",
    "Assets > Non-current > Investment in subsidiary > Distributions received",
    "Assets > Non-current > Investment in subsidiary > Capital contribution paid",
    "Assets > Non-current > Loan to subsidiary",
    "Assets > Non-current > Other non-current investments > HTM–quoted debt",
    "Assets > Non-current > Other non-current investments > AFS– quoted equity",
    "Assets > Current > Inventories > Raw materials and consumables",
    "Assets > Current > Inventories > Work in progress",
    "Assets > Current > Inventories > Finished goods",
    "Assets > Current > Trade and other receivables > Trade receivables from related parties",
    "Assets > Current > Trade and other receivables > Other trade receivables",
    "Assets > Current > Trade and other receivables > Amount due from subsidiary",
    "Assets > Current > Trade and other receivables > Prepayments and accrued income",
    "Assets > Current > Held-for-trading investments",
    "Assets > Current > Loan to subsidiary > Amount advanced to subsidiary",
    "Assets > Current > Loan to subsidiary > Capital contribution",
    "Assets > Current > Cash and bank balances > Cash at bank and on hand",
    "Assets > Current > Cash and bank balances > Bank overdraft",
    "Equity > Equity > Share capital",
    "Equity > Equity > Revaluation reserve",
    "Equity > Equity > Fair value reserve",
    "Equity > Equity > Retained earnings",
    "Equity > Current Year Profits & Losses > Revenue > Sale of goods",
    "Equity > Current Year Profits & Losses > Revenue > Rendering of services",
    "Equity > Current Year Profits & Losses > Cost of sales > Opening stock",
    "Equity > Current Year Profits & Losses > Cost of sales > Purchases",
    "Equity > Current Year Profits & Losses > Cost of sales > Carriage in",
    "Equity > Current Year Profits & Losses > Cost of sales > Closing stock",
    "Equity > Current Year Profits & Losses > Cost of sales > Other direct costs",
    "Equity > Current Year Profits & Losses > Cost of sales > Wages and salaries",
    "Equity > Current Year Profits & Losses > Cost of sales > Loose tools",
    "Equity > Current Year Profits & Losses > Cost of sales > Repairsand maintenance",
    "Equity > Current Year Profits & Losses > Cost of sales > Training and courses",
    "Equity > Current Year Profits & Losses > Cost of sales > Fuel and oil",
    "Equity > Current Year Profits & Losses > Cost of sales > Water and electricity",
    "Equity > Current Year Profits & Losses > Cost of sales > Professional fees",
    "Equity > Current Year Profits & Losses > Cost of sales > Insurances",
    "Equity > Current Year Profits & Losses > Cost of sales > Consumables",
    "Equity > Current Year Profits & Losses > Cost of sales > Depreciation",
    "Equity > Current Year Profits & Losses > Cost of sales > Provision for warranty costs",
    "Equity > Current Year Profits & Losses > Cost of sales > General expenses",
    "Equity > Current Year Profits & Losses > Sales and marketing expenses > Fairs and exhibitions",
    "Equity > Current Year Profits & Losses > Sales and marketing expenses > Advertising",
    "Equity > Current Year Profits & Losses > Sales and marketing expenses > Commissions payable",
    "Equity > Current Year Profits & Losses > Sales and marketing expenses > Market research and surveys",
    "Equity > Current Year Profits & Losses > Administrative expenses > Salaries",
    "Equity > Current Year Profits & Losses > Administrative expenses > Directors' remuneration",
    "Equity > Current Year Profits & Losses > Administrative expenses > Management fees",
    "Equity > Current Year Profits & Losses > Administrative expenses > Water andelectricity",
    "Equity > Current Year Profits & Losses > Administrative expenses > Repairs and maintenance",
    "Equity > Current Year Profits & Losses > Administrative expenses > Computer maintenance",
    "Equity > Current Year Profits & Losses > Administrative expenses > Office stationery and supplies",
    "Equity > Current Year Profits & Losses > Administrative expenses > Staff development",
    "Equity > Current Year Profits & Losses > Administrative expenses > Staff training",
    "Equity > Current Year Profits & Losses > Administrative expenses > Staff welfare",
    "Equity > Current Year Profits & Losses > Administrative expenses > Telecommunications",
    "Equity > Current Year Profits & Losses > Administrative expenses > Overseas travel",
    "Equity > Current Year Profits & Losses > Administrative expenses > Legal and professional fees",
    "Equity > Current Year Profits & Losses > Administrative expenses > Litigation settlement",
    "Equity > Current Year Profits & Losses > Administrative expenses > Audit fee",
    "Equity > Current Year Profits & Losses > Administrative expenses > Bank charges",
    "Equity > Current Year Profits & Losses > Administrative expenses > Insurance",
    "Equity > Current Year Profits & Losses > Administrative expenses > Subscriptions",
    "Equity > Current Year Profits & Losses > Administrative expenses > Baddebts written off",
    "Equity > Current Year Profits & Losses > Administrative expenses > Provision for doubtful debts",
    "Equity > Current Year Profits & Losses > Administrative expenses > Transport expenses",
    "Equity > Current Year Profits & Losses > Administrative expenses > General expenses",
    "Equity > Current Year Profits & Losses > Administrative expenses > Research costs",
    "Equity > Current Year Profits & Losses > Administrative expenses > Impairment loss on property, plant and equipment",
    "Equity > Current Year Profits & Losses > Administrative expenses > Depreciation",
    "Equity > Current Year Profits & Losses > Administrative expenses > Amortisation of intangible assets",
    "Equity > Current Year Profits & Losses > Other operating income > Rental income from operating leases",
    "Equity > Current Year Profits & Losses > Other operating income > Government grant",
    "Equity > Current Year Profits & Losses > Other operating income > Gain on disposal of property, plant and equipment",
    "Equity > Current Year Profits & Losses > Other operating income > Exchange gains",
    "Equity > Current Year Profits & Losses > Investment income > Interest income on cash and cash equivalents",
    "Equity > Current Year Profits & Losses > Investment income > Interest income from HFT investments",
    "Equity > Current Year Profits & Losses > Investment income > Interest income from HTM investments",
    "Equity > Current Year Profits & Losses > Investment income > Change in fair value of HFT investments",
    "Equity > Current Year Profits & Losses > Investment losses > Change in fair value of HFT investments",
    "Equity > Current Year Profits & Losses > Finance costs > Interest payable on finance lease",
    "Equity > Current Year Profits & Losses > Finance costs > Bank interest",
    "Equity > Current Year Profits & Losses > Finance costs > Dividends on redeemable cumulative preference shares",
    "Equity > Current Year Profits & Losses > Finance costs > Unwinding of discount on site restoration provision",
    "Equity > Current Year Profits & Losses > Share of profit of subsidiary",
    "Equity > Current Year Profits & Losses > Income tax expense > Current tax expense",
    "Equity > Current Year Profits & Losses > Income tax expense > Deferred tax expense",
    "Equity > Current Year Profits & Losses > PBT Expenses > Directors' remuneration",
    "Equity > Current Year Profits & Losses > PBT Expenses > Depreciation and amortisation expense",
    "Equity > Current Year Profits & Losses > PBT Expenses > Employee benefits expense",
    "Equity > Current Year Profits & Losses > PBT Expenses > Write-downs of inventories to net realisable value",
    "Equity > Current Year Profits & Losses > PBT Expenses > Impairment losses on property, plant and equipment",
    "Equity > Current Year Profits & Losses > PBT Expenses > Litigation settlement",
    "Equity > Current Year Profits & Losses > PBT Expenses > Audit fees",
    "Equity > Current Year Profits & Losses > PBT Expenses > Other assurance services",
    "Equity > Current Year Profits & Losses > PBT Expenses > Tax advisory services",
    "Equity > Current Year Profits & Losses > PBT Expenses > Other non-audit services",
    "Liabilities > Non-current > Borrowings > Redeemable preference shares",
    "Liabilities > Non-current > Borrowings > Finance lease obligations",
    "Liabilities > Non-current > Deferred tax liability",
    "Liabilities > Non-current > Provisions",
    "Liabilities > Current > Borrowings > Bank loan",
    "Liabilities > Current > Borrowings > Bank overdraft",
    "Liabilities > Current > Borrowings > Finance lease obligation",
    "Liabilities > Current > Trade and other payables > Trade payables",
    "Liabilities > Current > Trade and other payables > Other payables",
    "Liabilities > Current > Trade and other payables > Accrued expenses",
    "Liabilities > Current > Trade and other payables > Deferred government grant",
    "Liabilities > Current > Current tax liabilities",
    "Liabilities > Current > Provisions"
];

export const NEW_CLASSIFICATION_RULESET = [
  // 🏢 Assets
  "Assets > Non-current > Intangible assets",
  "Assets > Non-current > Property, plant and equipment",
  "Assets > Non-current > Investment property",
  "Assets > Non-current > Investment in subsidiary",
  "Assets > Non-current > Loan to subsidiary",
  "Assets > Non-current > Other non-current investments",

  "Assets > Current > Inventories",
  "Assets > Current > Trade and other receivables",
  "Assets > Current > Held-for-trading investments",
  "Assets > Current > Loan to subsidiary",
  "Assets > Current > Cash and bank balances",

  // 💰 Equity
  "Equity > Equity",
  "Equity > Current Year Profits & Losses",
  "Equity > Current Year Profits & Losses > Revenue",
  "Equity > Current Year Profits & Losses > Cost of sales",
  "Equity > Current Year Profits & Losses > Sales and marketing expenses",
  "Equity > Current Year Profits & Losses > Administrative expenses",
  "Equity > Current Year Profits & Losses > Other operating income",
  "Equity > Current Year Profits & Losses > Investment income",
  "Equity > Current Year Profits & Losses > Investment losses",
  "Equity > Current Year Profits & Losses > Finance costs",
  "Equity > Current Year Profits & Losses > Income tax expense",
  "Equity > Current Year Profits & Losses > PBT Expenses",

  // ⚖️ Liabilities
  "Liabilities > Non-current > Borrowings",
  "Liabilities > Non-current",
  "Liabilities > Current > Borrowings",
  "Liabilities > Current > Trade and other payables",
  "Liabilities > Current"
];
