-- Create admin user using the auth.users function properly
-- This ensures all required fields like confirmation_token are handled correctly

SELECT auth.uid(), auth.users();

-- Use the admin_create_user function if available, or insert with proper structure
INSERT INTO auth.users (
  instance_id,
  id,
  aud,
  role,
  email,
  encrypted_password,
  email_confirmed_at,
  confirmation_token,
  recovery_token,
  email_change_token_new,
  email_change,
  raw_app_meta_data,
  raw_user_meta_data,
  is_super_admin,
  created_at,
  updated_at,
  phone,
  phone_confirmed_at,
  phone_change,
  phone_change_token,
  phone_change_sent_at,
  confirmed_at,
  email_change_sent_at,
  email_change_token_current,
  email_change_confirm_status,
  banned_until,
  reauthentication_token,
  reauthentication_sent_at,
  is_sso_user,
  deleted_at
) VALUES (
  '00000000-0000-0000-0000-000000000000',
  gen_random_uuid(),
  'authenticated',
  'authenticated',
  'admin@auditportal.com',
  crypt('admin123', gen_salt('bf')),
  NOW(),
  '',
  '',
  '',
  '',
  '{"provider": "email", "providers": ["email"]}',
  '{"name": "System Administrator", "role": "admin"}',
  false,
  NOW(),
  NOW(),
  null,
  null,
  '',
  '',
  null,
  NOW(),
  null,
  '',
  0,
  null,
  '',
  null,
  false,
  null
);